FROM anapsix/alpine-java:8_server-jre_unlimited

MAINTAINER 646911949@qq.com

RUN mkdir -p /adouge

WORKDIR /adouge

EXPOSE 8101
ARG JAR_FILE
ADD ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urr
andom", "-jar", "app.jar"]
